let shopItemsData = [
  {
    id: "ok",
    name: "Blue shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/image-1.jpg",
  },
  {
    id: "o543k",
    name: "Black shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/image-2.jpg",
  },
  {
    id: "ok123",
    name: "White shirt",
    price: 60,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/image-5.jpg",
  },
  {
    id: "ok65",
    name: "Black shirt",
    price: 30,
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing.",
    img: "images/image-6.jpg",
  },
  {
    id: "essa420",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image-12.png",
  },
];
